tango_with_django/rango/urls.py
from rango import views
from django.urls import path

app_name = 'rango'

urlpatterns = [
	path('', views.index, name = 'index'),
	path('all', views.all, name = 'all'),
	path('login', views.user_login, name = 'login'),
	path('logout', views.user_logout, name = 'logout'),
	path('register', views.register, name = 'register'),
	path('about', views.about, name = 'about'),
	path('category/<str:category_name_url>', views.show_category, name = 'category'),
	path('add_category', views.add_category, name = 'add_category'),
	path('category/<str:category_name_url>/add_page', views.add_page, name = 'add_page')
]

tango_with_django/tango_with_django/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
	path('rango/', include('rango.urls')),
    path('admin/', admin.site.urls),
]

tango_with_django/rango/models.py
from django.db import models

from django.template.defaultfilters import slugify

from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
	name = models.CharField(max_length = 128, unique = True)
	views = models.IntegerField(default = 0)
	likes = models.IntegerField(default = 0)
	slug = models.SlugField(blank = True, unique = True)

	def save(self, *args, **kwargs):
		self.slug = slugify(self.name)
		super(Category, self).save(*args, **kwargs)

	class Meta:
		verbose_name_plural = 'categories'

	def __str__(self):
		return self.name
	
class Page(models.Model):
	views = models.IntegerField(default = 0)
	title = models.CharField(max_length = 128)
	category = models.ForeignKey('Category', on_delete = models.CASCADE)
	url = models.URLField()

	class Meta:
		verbose_name_plural = 'All Pages'

	def __str__(self):
		return self.title

class UserProfile(models.Model):
	user = models.OneToOneField(User, on_delete = models.CASCADE)
	website = models.URLField(blank = True)
	picture = models.ImageField(upload_to = 'profile_images', blank = True)

	def __str__(self):
		return self.user.username

tango_with_django/rango/forms.py
from django import forms
from django.contrib.auth.models import User
from rango.models import Category, Page, UserProfile

class CategoryForm(forms.ModelForm):
	name = forms.CharField(max_length = 128, help_text = 'Please enter the name of Category')
	views = forms.IntegerField(widget = forms.HiddenInput(), initial = 0)
	likes = forms.IntegerField(widget = forms.HiddenInput(), initial = 0)
	slug = forms.CharField(widget = forms.HiddenInput(), required = False)

	class Meta:
		model = Category
		fields = ('name', )

class PageForm(forms.ModelForm):
	title = forms.CharField(max_length = 128, help_text = 'Please enter the title of the Page')
	views = forms.IntegerField(widget = forms.HiddenInput(), initial = 0)
	url = forms.URLField(max_length = 200, help_text = 'Please enter the url for the Page')

	class Meta:
		model = Page
		exclude = ('category', )

class UserForm(forms.ModelForm):
	password = forms.CharField(widget = forms.PasswordInput())

	class Meta:
		model = User
		fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):

	class Meta:
		model = UserProfile
		fields = ('website', 'picture')

tango_with_django/rango/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Category, Page, UserProfile
from .forms import CategoryForm, PageForm, UserForm, UserProfileForm
from django.contrib.auth import login, authenticate, logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required

def index(request):
	cat = Category.objects.order_by('-likes')[:5]
	pages = Page.objects.order_by('-views')[:5]
	context_dict = {'categories': cat,
					'pages': pages}
	return render(request, 'rango/index.html', context_dict)

def about(request):
	context_dict = {'msg': 'hello dear friends'}
	return render(request, 'rango/about.html', context = context_dict)


def show_category(request, category_name_url):
	context_dict = {}
	try:
		cat = Category.objects.get(slug = category_name_url)
		pages = Page.objects.filter(category = cat)
		context_dict['pages'] = pages
		context_dict['category'] = cat
	except Category.DoesNotExist:
		context_dict['pages'] = None
		context_dict['category'] = None
	return render(request, 'rango/category.html', context_dict)

@login_required
def add_category(request):
	if request.method == 'POST':
		form = CategoryForm(request.POST)
		if form.is_valid():
			form.save(commit = True)
			return HttpResponseRedirect(reverse('rango:index'))
	else:
		form = CategoryForm()
	return render(request, 'rango/add_category.html', {'form': form})

@login_required
def add_page(request, category_name_url):
	cat = get_object_or_404(Category, slug = category_name_url)
	if request.method == 'POST':
		form = PageForm(request.POST)
		if form.is_valid():
			page = form.save(commit = False)
			page.category = cat
			page.save()
			return HttpResponseRedirect(reverse('rango:category', kwargs={'category_name_url': category_name_url}))
	else:
		form = PageForm()
	context_dict = {'form': form, 'cat': cat}
	return render(request, 'rango/add_page.html', context_dict)

def register(request):

	registered = False

	if request.method == 'POST':
		user_form = UserForm(request.POST)
		profile_form = UserProfileForm(request.POST)

		if user_form.is_valid() and profile_form.is_valid():
			user = user_form.save(commit = False)
			user.set_password(user.password)
			user.save()

			profile = profile_form.save(commit = False)
			profile.user = user

			if 'picture' in request.FILES:
				profile.picture = request.FILES['picture']

			profile.save()
			registered = True	
			return HttpResponseRedirect(reverse('rango:login'))

	else:
		user_form = UserForm()
		profile_form = UserProfileForm()
	context_dict = {'user_form': user_form,
					'profile_form': profile_form,
					'registered': registered}
	return render(request, 'rango/register.html', context_dict)

def user_login(request, prompt = False):
	if request.method == 'POST' and not prompt:
		username = request.POST.get('username')
		password = request.POST.get('password')

		user = authenticate(username = username, password = password)

		if user:
			if user.is_active:
				login(request, user)
				return HttpResponseRedirect(reverse('rango:index'))
			else:
				return HttpResponse("Account is disabled")
		else:
			return user_login(request, True)
	else:
		return render(request, 'rango/login.html', {'prompt': prompt})

def user_logout(request):
	logout(request)
	return HttpResponseRedirect(reverse('rango:index'))

def all(request):
	cats = Category.objects.all()
	context_dict = {'categories': cats}
	return render(request, 'rango/all.html', context_dict)

tango_with_django/templates/rango/about.html
{% extends 'rango/base.html' %}
{% load static %}
{% block title_block %}
	About Us
{% endblock %}

{% block body_block %}
	<h1 class="text-center">Welcome to About Us Page</h1>
	<p class="text-center">This tutorial has been put together by <strong>Pavitra</strong></p>
	<div class="text-center">
		<img class="rounded-circle img-responsive" src="{% static "images/about.jpg"%}" alt="Boy Standing in Grass">
	</div>
{% endblock %}

tango_with_django/templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load static %}
{% block title_block %}
	Add a Category
{% endblock %}
{% block body_block %}
	<h1 class="text-center">Add a Category</h1>
	<div class="text-center">
		<form id="category_form" method="POST" action="{% url 'rango:add_category' %}">
			{% csrf_token %}
			{% for hidden in form.hidden_fields %}
				{{ hidden }}
			{% endfor %}
			{% for field in form.visible_fields %}
				{{ field.errors }}
				{{ field.help_text }}
				{{ field }}
			{% endfor %}
			<input type="submit" name="submit" value="Create Category">
		</form>
	</div>
{% endblock %}

tango_with_django/templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% load static %}
{% block title_block %}
	Add a Page
{% endblock %}
{% block body_block %}
	<h1 class="text-center">Add a Page</h1>
	<div class="text-center">
		<form id="page_form" method="POST" action="{% url 'rango:add_page' cat.slug %}">
			{% csrf_token %}
			{% for hidden in form.hidden_fields %}
				{{hidden}}
			{% endfor %}
			{% for field in form.visible_fields %}
				{{field.error}}
				{{field.help_text}}
				{{field}}<br><br>
			{% endfor %}
			<input class="btn btn-primary" type="submit" name="submit" value="Add Page">
		</form>
	</div>
{% endblock %}

tango_with_django/templates/rango/all.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
	Categories
{% endblock %}

{% block body_block %}
	{% if categories %}
		<h2 class="text-center">Categories</h2>
		<ul class="text-center" style="list-style-type: none; margin-top: 20px">
			{% for cat in categories %}
				<li>
					<a href="{% url 'rango:category' cat.slug %}">{{cat.name}}
					</a>
				</li>
			{% endfor %}
		</ul>
	{% else %}
		<h2 class="text-center">No categories are added yet</h2>
	{% endif %}
	<div class="text-center">
		<a class="btn btn-outline-primary" href="{% url 'rango:add_category' %}">Add Category</a>
	</div>
{% endblock %}

tango_with_django/templates/rango/base.html
{% load rango_template_tags %}
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>
		Rango - 
		{% block title_block %}
			Tango With Django
		{% endblock %}
	</title>
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
	<!--
	<link rel="stylesheet" type="text/css" href="{% static "css/style.css"%}"> -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
	<nav class="navbar navbar-expand-md bg-dark navbar-dark">
	  <!-- Brand -->
	  <a class="navbar-brand" href="{% url 'rango:index' %}">Rango</a>

	  <!-- Toggler/collapsibe Button -->
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <!-- Navbar links -->
	  <div class="collapse navbar-collapse" id="collapsibleNavbar">
	    <ul class="navbar-nav">
	      <li class="nav-item">
	        <a class="nav-link" href="{% url 'rango:about' %}">About</a>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link" href="{% url 'rango:all' %}">All Categories</a>
	      </li>
	      	{% if user.is_authenticated %}
		      	<li class="nav-item">
		        	<a class="nav-link" href="{% url 'rango:logout' %}">Logout <strong>{{user.username}}</strong></a>
		        </li>
	        {% else %}
		      	<li class="nav-item">
		        	<a class="nav-link" href="{% url 'rango:login' %}">Login</a>
		        </li>
		        
		      	<li class="nav-item">
		        	<a class="nav-link" href="{% url 'rango:register' %}">Register</a>
		        </li>
	        {% endif %}
	    </ul>
	  </div>
	</nav> 


	<div class="container">
		{% block body_block %}
		{% endblock %}
	</div>

	 




	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<!-- Popper JS -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
</body>
</html>

tango_with_django/templates/rango/category.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
	{{category.name}}
{% endblock %}
{% block body_block %}
	<div>
	{% if category %}
		<h1 class="text-center" >{{category.name}}</h1>
		{% if pages %}
			<ul style="display: table; margin: 0 auto;">
			{% for page in pages %}
				<li><a href="{{page.url}}">{{page.title}}</a></li>
			{% endfor %}
			</ul>
		{% else %}
			<h3 class="text-center">{{category.name}} has no pages</h3>
		{% endif %}
		<br>
		<div class="text-center">
			<a class="btn btn-outline-danger" href="{% url 'rango:add_page' category.slug %}">Add Page
			</a>
		</div>
		{% else %}
		<h1>Invalid Category</h1>
	{% endif %}
	</div>
{% endblock %}

tango_with_django/templates/rango/index.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
	Home Page
{% endblock %}

{% block body_block%}
	<div class="jumbotron text-center">
		<h1>Rango says Hey there 
			{% if user.is_authenticated %}
				<strong>{{user.username}}</strong>
			{% else %}
				Partner
			{% endif %}
		</h1>
	</div> 

	<div class="row">
		<div class="col-sm-6">
			{% if categories %}
				<h3 class="text-center">Top Categories</h3>
				<ul>
					{% for cat in categories %}
						<li>
							<a href="{% url 'rango:category' cat.slug %}">{{cat.name}}</a>
						</li>
					{% endfor %}
				</ul>
			{% else %}
				<h3 class="text-center">No Categories Present</h3>
			{% endif %}
			<div class="text-center">
				<a class="btn btn-outline-primary text-center" href="{% url 'rango:add_category' %}">Add Category</a><br>
			</div>
		</div>
		<div class="col-sm-6">
			{% if pages %}
				<h3 class="text-center">Top Pages</h3>
				<ul>
					{% for page in pages %}
						<li>
							<a href="{{page.url}}">{{page.title}}</a>
						</li>
					{% endfor %}
				</ul>
			{% else %}
				<h3 class="text-center">No Pages Present</h3>
			{% endif %}	
		</div>
	</div>
	<br>
	<div class="text-center">
		<img class="img-fluid rounded-circle" src="{% static "images/avengers.jpg" %}"
alt="Picture of Avengers"/>
	</div>
{% endblock %}

tango_with_django/templates/rango/login.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
	Login
{% endblock %}

{% block body_block %}
	{% if prompt %}
		<h1 class="text-center">Please enter correct credentials</h1><br>
	{% endif %}
	<h1 class="text-center">Login</h1>
	<div class="text-center">
		<form method="POST" action="{% url 'rango:login' %}">
			{% csrf_token %}
			<input type="text" name="username" placeholder="Username"><br>
			<input type="password" name="password" placeholder="Password"><br><br>
			<input class="btn btn-outline-primary" type="submit" name="submit" value="Login">
		</form>
	</div>
{% endblock %}

tango_with_django/templates/rango/register.html
{% extends 'rango/base.html' %}

{% block title_block %}
	Register
{% endblock %}

{% block body_block %}
	{% if registered %}
		<h2 class="text-center">You are successfully registered!</h2>
	{% else %}
		<div class="text-center">
			<form method="POST" action="{% url 'rango:register' %}" enctype="multipart/form-data">
				{% csrf_token %}
				{% for hidden in user_form.hidden_fields %}
					{{hidden}}
				{% endfor %}

				{% for field in user_form.visible_fields %}
					{{field.name}}
					{{field}}<br>
					{{fields.help_text}}<br>
				{% endfor %}
				{{ profile_form.as_p }}
				<input class="btn btn-outline-primary" type="submit" name="submit" value="Register">
			</form>
		</div>
	{% endif %}

{% endblock %}