blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = 'myblog'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myblog/', include('myblog.urls')),
]

blog/myblog/urls.py
from django.urls import path, include
from myblog import views

app_name = 'myblog'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('editpost/<int:pk>', views.editpost, name = 'editpost'),
    path('register', views.register, name = 'register'),
    path('login', views.user_login, name = 'login'),
    path('logout', views.user_logout, name = 'logout'),
    path('addpost', views.addpost, name = 'addpost'),
]

blog/myblog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class Post(models.Model):
	author = models.ForeignKey(User, on_delete = models.CASCADE)
	title = models.CharField(max_length = 500)
	text = models.TextField()
	created_date = models.DateTimeField(default = timezone.now)
	published_date = models.DateTimeField(blank = True, null = True)

	class Meta:
		unique_together = ('author', 'title')
	def __str__(self):
		return self.title

blog/myblog/forms.py
from django import forms

from myblog.models import Post
from django.contrib.auth.models import User

class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = ('title', 'text', )

class UserForm(forms.ModelForm):

	password = forms.CharField(widget = forms.PasswordInput())

	class Meta:
		model = User
		fields = ('username', 'email', 'password')

blog/myblog/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from myblog.models import Post
from myblog.forms import PostForm, UserForm
from django.utils import timezone

posts = None

def index(request):
	global posts
	if request.user.is_active:
		posts = Post.objects.filter(author = request.user).order_by('-published_date')
	context_dict = {'posts': posts}
	return render(request, 'myblog/index.html', context_dict)

def register(request):
	if request.method == 'POST':
		user_form = UserForm(request.POST)
		if user_form.is_valid():
			user = user_form.save(commit = True)
			user.set_password(user.password)
			user.save()
			return HttpResponseRedirect(reverse('myblog:login'))
	else:
		user_form = UserForm()
	context_dict = {'user_form': user_form}
	return render(request, 'myblog/register.html', context_dict)


def user_login(request):
	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')
		user = authenticate(username = username, password = password)
		if user:
			if user.is_active:
				login(request, user)
				global posts
				posts = Post.objects.filter(author = user).order_by('-published_date')
				return HttpResponseRedirect(reverse('myblog:index'))
			else:
				return HttpResponse("Your account is disabled")
		else:
			return HttpResponse("Please enter valid credentials")
	else:
		return render(request, 'myblog/login.html', {})
		
def user_logout(request):
	logout(request)
	global posts
	posts = None
	return HttpResponseRedirect(reverse('myblog:index'))

def addpost(request):
	if request.method == 'POST':
		post_form = PostForm(request.POST)
		if post_form.is_valid():
			post = post_form.save(commit = False)
			post.published_date = timezone.now();
			post.author = request.user
			post.save()
			global posts
			posts = Post.objects.filter(author = request.user).order_by('-published_date')
			return HttpResponseRedirect(reverse('myblog:index'))
		else:
			context_dict = {'post_form': post_form}
			return render(request, 'myblog/addpost.html', context_dict)
	else:
		post_form = PostForm()
		context_dict = {'post_form': post_form}
		return render(request, 'myblog/addpost.html', context_dict)

def editpost(request, pk):
	post = get_object_or_404(Post, pk = pk)
	if request.method == 'POST':
		post_form = PostForm(request.POST, instance = post)
		if post_form.is_valid():
			post = post_form.save(commit = False)
			post.published_date = timezone.now();
			post.author = request.user
			post.save()
			global posts
			posts = Post.objects.filter(author = request.user).order_by('-published_date')
			return HttpResponseRedirect(reverse('myblog:index'))
		else:
			context_dict = {'post_form': post_form}
			return render(request, 'myblog/editpost.html', context_dict)
	else:
		post_form = PostForm(instance = post)
		context_dict = {'post_form': post_form, 'pk': pk}
		return render(request, 'myblog/editpost.html', context_dict)

blog/templates/myblog/addpost.html
{% extends 'myblog/base.html' %}
{% load static %}

{% block title_block %}
	Add a Post
{% endblock %}

{% block body_block %}
	<div class="text-center">
		{% if pk %}
			<h2>Edit Post</h2>
		{% else%}
			<h2>New  Post</h2>
		{% endif %}
		<form method="POST" action="{% url 'myblog:addpost' %}">
			{% csrf_token %}
			{{post_form.as_p}}
			<input class="btn btn-primary" type="submit" name="submit" value="Save Post">
		</form>
	</div>
{% endblock %}

blog/templates/myblog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>
		{% block title_block %}
		{% endblock %}
	</title>
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static "styles/basestyle.css"%}">
</head>
<body>

	{% if user.is_authenticated %}
		<nav class="navbar navbar-expand-md bg-dark navbar-dark">
		  <!-- Brand -->
		  <a class="navbar-brand" href="{% url 'myblog:index' %}">Home</a>

		  <!-- Toggler/collapsibe Button -->
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
		    <span class="navbar-toggler-icon"></span>
		  </button>

		  <!-- Navbar links -->
		  <div class="collapse navbar-collapse" id="collapsibleNavbar">
		    <ul class="navbar-nav">
		      <li class="nav-item">
		        <a class="nav-link" href="{% url 'myblog:addpost' %}">New Post</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link" href="{% url 'myblog:logout' %}">Logout {{user.username}}</a>
		      </li>
		    </ul>
		  </div>
		</nav> 

	{% else %}

		<nav class="navbar navbar-expand-md bg-dark navbar-dark">
		  <!-- Brand -->
		  <a class="navbar-brand" href="{% url 'myblog:index' %}">Home</a>

		  <!-- Toggler/collapsibe Button -->
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
		    <span class="navbar-toggler-icon"></span>
		  </button>

		  <!-- Navbar links -->
		  <div class="collapse navbar-collapse" id="collapsibleNavbar">
		    <ul class="navbar-nav">
		      <li class="nav-item">
		        <a class="nav-link" href="{% url 'myblog:login' %}">Login</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link" href="{% url 'myblog:register' %}">Signup</a>
		      </li>
		    </ul>
		  </div>
		</nav> 

	{% endif %}
	<div id="page-container" class="container">

		<div id="content-wrap">
			{% block body_block %}

			{% endblock %}
		</div>
		<!-- Footer -->
		<footer id="footer" class="text-center">

		  <!-- Footer Elements -->
		  	<div class="col-md-12">
	            <ul class="social-network social-circle">
	                <li><a href="https://instagram.com/fitaholic_pavi" class="icoRss bg-dark" title="Instagram"><i class="fa fa-instagram"></i></a></li>
	                <li><a href="https://www.facebook.com/pavitra.agarwal.14" class="icoFacebook bg-dark" title="Facebook"><i class="fa fa-facebook"></i></a></li>
	                <li><a href="https://linkedin.com/in/agarwalpavitra" class="icoLinkedin bg-dark" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
	            </ul>				
			</div>
		  <!-- Footer Elements -->

		  <!-- Copyright -->
		  <div class="footer-copyright text-center py-3">© 2020 Copyright:
		    <strong>fitaholic_pavi</strong>
		  </div>
		  <!-- Copyright -->

		</footer>
	</div>
	<!-- Footer -->
	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<!-- Popper JS -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
</body>
</html>

blog/templates/myblog/editpost.html
{% extends 'myblog/base.html' %}
{% load static %}

{% block title_block %}
	Edit Post {{post.title}}
{% endblock %}

{% block body_block %}
	<div class="text-center">
		<h2>Edit Post</h2>
		<form method="POST" action="{% url 'myblog:editpost' pk%}">
			{% csrf_token %}
			{{post_form.as_p}}
			<input class="btn btn-primary" type="submit" name="submit" value="Save Post">
		</form>
	</div>
{% endblock %}

blog/templates/myblog/index.html
{% extends 'myblog/base.html' %}
{% load static %}

{% block title_block %}
	Pavitra's Blog
{% endblock %}

{% block body_block %}
	<h1 class="jumbotron text-center" style="font-family: Lobster;">Welcome to Blogs!!</h1>
	{% if not user.is_authenticated %}
		<div class="row">
			<div class="col-sm-6 text-center">
				<h3>Have an account Login Here</h3>
				<br>
				<a class="btn btn-primary" href="{% url 'myblog:login' %}">Login</a>
			</div>
			<div class="col-sm-6 text-center">
				<h3>New User Signup Here</h3>
				<br>
				<a class="btn btn-primary" href="{% url 'myblog:register' %}">Signup</a>
			</div>
		</div>
	{% else %}
		{% if posts %}
			{% for post in posts %}
				<div>
					<h3 style="font-family: Lobster; font-style: italic;">
						<a href="{% url 'myblog:editpost' post.pk %}">{{post.title}}</a>
					</h3>
					<p style="font-size: 0.9em; color: grey;">
						published: {{post.published_date}}
					</p>
					<p style="font-family: Lobster;">{{post.text}}</p>
				</div>
				<hr>
			{% endfor %}
		{% else %}
			<h3 class="text-center">You have not created any blogs yet</h3><br>
			<div class="text-center">
				<a class="btn btn-primary" href="{% url 'myblog:addpost' %}">Create a Post</a>
			</div>
		{% endif %}
	{% endif %}
{% endblock %}

blog/templates/myblog/login.html
{% extends 'myblog/base.html' %}
{% load static %}

{% block title_block %}
	LOGIN
{% endblock %}

{% block body_block %}
	<div class="text-center" style="width: 30%; margin: 0 auto;">
		<br>
		<form class="form-signin" method="POST" action="{% url 'myblog:login' %}">
			{% csrf_token %}
	     	<img class="mb-4" src="{% static "images/login" %}" alt="" width="72" height="72">
	     	<h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
	     	<label for="inputEmail" class="sr-only">Email address</label>
	     	<input type="text" class="form-control" placeholder="Username" name="username" required autofocus>
	     	<label for="inputPassword" class="sr-only">Password</label>
	     	<input type="password" name="password" class="form-control" placeholder="Password" required>
	     	<br>
	      	<button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
	    </form>
	</div>
{% endblock %}

blog/templates/myblog/register.html
{% extends 'myblog/base.html' %}
{% load static %}

{% block title_block %}
	Register
{% endblock %}

{% block body_block %}
	<h1 class="jumbotron text-center" style="font-family: Lobster;">Register for Blogs!!</h1>
	<div style="display: table; margin: 0 auto;">
		<form method="POST" action="{% url 'myblog:register' %}">
			{% csrf_token %}
			<table>
				{{ user_form.as_table }}
			</table>
			<br>
			<input type="submit" name="submit" class="btn btn-success" value="Signup">
		</form>
	</div>
{% endblock %}